# Generated by Django 2.2 on 2019-05-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['Department_number', 'Department_name']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name', 'nickname']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['section', 'patient']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['department__department_number', 'section_name', 'season__season_name']},
        ),
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(default=1111, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='hospitalinfo.Department'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('Department_number', 'Department_name')},
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('last_name', 'first_name')},
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('last_name', 'first_name', 'nickname')},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('section', 'patient')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('season', 'department', 'section_name')},
        ),
        migrations.RemoveField(
            model_name='section',
            name='patient',
        ),
    ]
